//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISForTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int idQuestion { get; set; }
        public string TextQuestion { get; set; }
        public Nullable<int> idWork { get; set; }
    
        public virtual Work Work { get; set; }
    }
}
